#import "../../common.typ": *

#hl[What is SPI?]

SPI is a *synchronous*, *full-duplex*, *master-slave* serial bus. Unlike UART, a shared *clock line* is provided by the master — no baud rate agreement needed.

#v(0.7em)
#grid(
  columns: (1fr, 1fr, 1fr, 1fr),
  gutter: 0.8em,
  rect(fill: accent.lighten(80%), stroke: accent, radius: 6pt, inset: 11pt)[
    #text(weight: "bold", fill: accent)[Synchronous] \
    #text(size: 14pt)[Clock driven by master. Both sides latch on the same edge.]
  ],
  rect(fill: accent.lighten(80%), stroke: accent, radius: 6pt, inset: 11pt)[
    #text(weight: "bold", fill: accent)[Full-Duplex] \
    #text(size: 14pt)[Data flows in both directions simultaneously on separate wires.]
  ],
  rect(fill: accent.lighten(80%), stroke: accent, radius: 6pt, inset: 11pt)[
    #text(weight: "bold", fill: accent)[Master-Slave] \
    #text(size: 14pt)[Master controls the clock and selects which slave talks.]
  ],
  rect(fill: accent.lighten(80%), stroke: accent, radius: 6pt, inset: 11pt)[
    #text(weight: "bold", fill: accent)[No Addressing] \
    #text(size: 14pt)[Slaves are selected by a dedicated chip select (CS) line.]
  ],
)

#v(0.7em)
Common uses: flash memory, SD cards, ADCs/DACs, displays, sensors.

---

#hl[SPI Signal Lines]

SPI uses *4 wires* (plus ground):

#v(0.5em)
#set text(size: 17pt)
#table(
  columns: (0.8fr, 0.8fr, 1.8fr),
  fill: (_, row) => if row == 0 { accent } else if calc.odd(row) { light } else { white },
  stroke: 0.5pt + luma(180),
  inset: 8pt,
  align: (center, center, left),
  text(fill: white, weight: "bold")[Signal],
  text(fill: white, weight: "bold")[Dir],
  text(fill: white, weight: "bold")[Description],

  [SCLK], [M→S], [Serial Clock — generated by master],
  [MOSI], [M→S], [Master Out Slave In — data to slave],
  [MISO], [S→M], [Master In Slave Out — data from slave],
  [CS/SS], [M→S], [Chip Select — *active low*, selects slave],
)

#v(0.5em)
#text(size: 15pt, fill: luma(120))[
  #_icons.important Some datasheets use SDI/SDO or DIN/DOUT instead of MOSI/MISO.\
  #_icons.important CS is sometimes called SS (Slave Select) or NSS (active low implied).
]

---

#align(center)[#image("../../images/spi-bus.svg", width: 70%)]

---

#hl[How a Transfer Works]

  #set enum(numbering: "1.")
  + Master pulls *CS Low* to select the slave
  + Master generates *clock pulses* on SCLK
  + On each clock cycle:
  - Master shifts one bit out on *MOSI*
  - Slave shifts one bit out on *MISO*
  + After all bits, master releases *CS High*

  #v(0.5em)
  Both devices shift simultaneously through an internal shift register —
  it's essentially a *circular exchange* of bytes.

  #v(0.4em)
  #note[Even if you only want to *read*, you must still clock out dummy bytes on MOSI to generate the clock.]

  /*
  #rect(fill: light, radius: 4pt, inset: 10pt)[
    #set text(font: "Fira Code", size: 10pt)
    ```
    CS   ──┐               ┌──
    └───────────────┘

    SCLK    ┌─┐ ┌─┐ ┌─┐ ┌─┐
    │ │ │ │ │ │ │ │
    ───┘ └─┘ └─┘ └─┘ └─

    MOSI ───[b7][b6][b5]...[b0]

    MISO ───[b7][b6][b5]...[b0]
    ```
  ]
*/

---

#hl[SPI Clock Modes (CPOL & CPHA)]

Two parameters control timing. Each has 2 options → *4 modes* total.

#v(0.4em)
#grid(
  columns: (1fr, 1fr),
  gutter: 1em,
  rect(fill: accent.lighten(85%), stroke: accent, radius: 6pt, inset: 11pt)[
    #text(weight: "bold", fill: accent)[CPOL — Clock Polarity] \
    #v(0.2em)
    #text(size: 16pt)[
      *CPOL=0* → clock idles *Low* \
      *CPOL=1* → clock idles *High*
    ]
  ],
  rect(fill: accent.lighten(85%), stroke: accent, radius: 6pt, inset: 11pt)[
    #text(weight: "bold", fill: accent)[CPHA — Clock Phase] \
    #v(0.2em)
    #text(size: 16pt)[
      *CPHA=0* → data sampled on *leading* edge \
      *CPHA=1* → data sampled on *trailing* edge
    ]
  ],
)

#v(0.5em)
#set text(size: 16pt)
#table(
  columns: (0.6fr, 0.6fr, 0.6fr, 0.8fr, 0.8fr, 1.5fr),
  fill: (_, row) => if row == 0 { accent } else if calc.odd(row) { light } else { white },
  stroke: 0.5pt + luma(180),
  inset: 7pt,
  align: center,
  text(fill: white, weight: "bold")[Mode],
  text(fill: white, weight: "bold")[CPOL],
  text(fill: white, weight: "bold")[CPHA],
  text(fill: white, weight: "bold")[Idle Clock],
  text(fill: white, weight: "bold")[Sample On],
  text(fill: white, weight: "bold")[Common Use],

  [0], [0], [0], [Low], [Rising edge], [Most sensors, SD cards],
  [1], [0], [1], [Low], [Falling edge], [Some ADCs],
  [2], [1], [0], [High], [Falling edge], [Some flash chips],
  [3], [1], [1], [High], [Rising edge], [Some displays],
)

---

#align(center)[
#grid(
  columns: (auto, auto),
  rows: (auto, auto),
  gutter: 0.1em,
  image("../../images/spi-mode0.svg", width: 80%),
  image("../../images/spi-mode1.svg", width: 80%),
  image("../../images/spi-mode2.svg", width: 80%),
  image("../../images/spi-mode3.svg", width: 80%),
)]

// #important[Master and slave *must* use the same mode. Check the slave's datasheet — most sensors default to Mode 0.]

---

#hl[Multiple Slaves]

#grid(columns: (1fr, 1fr), gutter: 1.5em)[
  *Independent CS lines* _(most common)_

  Each slave has its own CS pin on the master. SCLK, MOSI, MISO are shared. Only one CS is pulled low at a time.

  /*
  #rect(fill: light, radius: 4pt, inset: 10pt)[
    #set text(font: "Fira Code", size: 10pt)
    ```
    Master
    SCLK ──┬──────┬──────
    MOSI ──┼──────┼──────
    MISO ──┼──────┼──────
    CS0  ──► Slave0
    CS1  ──────────► Slave1
    ```
  ]
  */

  #text(fill: signal-high, weight: "bold")[Pro:] Simple, fast, independent. \
  #text(fill: signal-low, weight: "bold")[Con:] One CS pin per slave on master.
][
  *Daisy-chain* _(less common)_

  Slaves are chained: MISO of one feeds MOSI of the next. A single CS activates all. Data ripples through the chain.

/*
  #rect(fill: light, radius: 4pt, inset: 10pt)[
    #set text(font: "Fira Code", size: 10pt)
    ```
    Master
    MOSI ──► Slave0 ──► Slave1
    MISO ◄────────────── Slave1
    CS   ──────────────► both
    ```
  ]
  */

  #text(fill: signal-high, weight: "bold")[Pro:] Only 1 CS line needed. \
  #text(fill: signal-low, weight: "bold")[Con:] All slaves must support it;\
  latency increases with chain length.
]

#slide[
#hl[SPI — Pros & Cons]

#grid(
  columns: (1fr, 1fr),
  gutter: 1.5em,
  rect(fill: signal-high.lighten(75%), stroke: signal-high, radius: 6pt, inset: 14pt)[
    #set text(size: 17pt)
    - *Fast* — few MHz to 100 MHz, no protocol overhead
    - *Simple* hardware and firmware
    - *Full-duplex* — read and write simultaneously
    - No addressing logic — CS line handles selection
    - Works with almost any slave device
  ],
  rect(fill: signal-low.lighten(75%), stroke: signal-low, radius: 6pt, inset: 14pt)[
    #set text(size: 17pt)
    - *4 wires minimum* — grows with slave count (CS pins)
    - No acknowledgement — master can't detect absent slave
    - No built-in error detection (no parity, no CRC in protocol)
    - Short distances only — no defined max cable length
    - No multi-master support in standard spec
  ],
)

#url-block("codes/spi.jl")
]
---

#hl[SPI vs UART vs I²C]

#set text(size: 16pt)
#table(
  columns: (1.4fr, 1fr, 1fr, 1fr),
  fill: (_, row) => if row == 0 { accent } else if calc.odd(row) { light } else { white },
  stroke: 0.5pt + luma(180),
  inset: 8pt,
  align: (left, center, center, center),
  text(fill: white, weight: "bold")[Feature],
  text(fill: white, weight: "bold")[SPI],
  text(fill: white, weight: "bold")[UART],
  text(fill: white, weight: "bold")[I²C],

  [Clock], [Shared (master)], [None (async)], [Shared (master)],
  [Wires (2 nodes)], [4], [2], [2],
  [Duplex], [Full], [Full], [Half],
  [Speed], [Up to 100 MHz], [Up to ~1 Mbps], [Up to 5 Mbps (FM+)],
  [Multi-slave], [CS per slave], [Point-to-point], [Address per slave],
  [Addressing], [Hardware CS], [None], [7/10-bit address],
  [Hardware cost], [Low], [Very low], [Low],
  [Complexity], [Low], [Very low], [Medium],
)
